name: Review PRs Scheduler

on:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  trigger-review:
    runs-on: ubuntu-latest
    steps:
      - name: Process Review Queue
        env:
          GH_PAT: ${{ secrets.GOWREESH_TOKEN }}
          GIST_ID_QUEUE: ${{ secrets.GIST_ID_QUEUE }}
          GIST_ID_REVIEW_HISTORY: ${{ secrets.GIST_ID_REVIEW_HISTORY }}
        run: |
          echo "Fetching queue and review history..."
          curl -s -H "Authorization: token $GH_PAT" https://api.github.com/gists/$GIST_ID_QUEUE > gist_queue.json
          curl -s -H "Authorization: token $GH_PAT" https://api.github.com/gists/$GIST_ID_REVIEW_HISTORY > gist_history.json

          QUEUE=$(jq -r '.files["queue.json"].content' gist_queue.json | jq '.')
          HISTORY=$(jq -r '.files["review-history.json"].content' gist_history.json | jq '.')

          # Calculate time bounds
          NOW=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          ONE_HOUR_AGO=$(date -u -d "1 hour ago" +"%Y-%m-%dT%H:%M:%SZ")

          # Filter review history for last hour
          RECENT_REVIEWS=$(echo "$HISTORY" | jq "[.[] | select(.timestamp >= \"$ONE_HOUR_AGO\")]")
          COUNT=$(echo "$RECENT_REVIEWS" | jq length)

          echo "Reviews in the last hour: $COUNT"

          if [ "$COUNT" -ge 4 ]; then
            echo "Rate limit reached. Exiting."
            exit 0
          fi

          # Pick next PR
          PR_TO_REVIEW=$(echo "$QUEUE" | jq '.[0]')
          if [ "$PR_TO_REVIEW" == "null" ]; then
            echo "No PRs to review."
            exit 0
          fi

          REPO=$(echo "$PR_TO_REVIEW" | jq -r '.repo')
          PR_NUMBER=$(echo "$PR_TO_REVIEW" | jq -r '.pr')

          echo "Reviewing PR #$PR_NUMBER from $REPO"

          # Post review comment
          curl -s -X POST -H "Authorization: token $GH_PAT" \
            -H "Content-Type: application/json" \
            -d '{"body": "@coderabbitai review"}' \
            "https://api.github.com/repos/$REPO/issues/$PR_NUMBER/comments"

          # Update review history
          NEW_REVIEW=$(jq -n --arg pr "$PR_NUMBER" --arg timestamp "$NOW" '{pr: $pr, timestamp: $timestamp}')
          UPDATED_HISTORY=$(echo "$HISTORY" | jq ". + [ $NEW_REVIEW ]")
          echo "$UPDATED_HISTORY" > review-history.json

          curl -s -X PATCH -H "Authorization: token $GH_PAT" \
            -H "Content-Type: application/json" \
            -d "$(jq -n --arg content "$(cat review-history.json | jq -Rs .)" \
              '{files: {"review-history.json": {"content": $content}}}')" \
            https://api.github.com/gists/$GIST_ID_REVIEW_HISTORY

          # Remove from queue
          UPDATED_QUEUE=$(echo "$QUEUE" | jq 'del(.[0])')
          echo "$UPDATED_QUEUE" > updated-queue.json

          curl -s -X PATCH -H "Authorization: token $GH_PAT" \
            -H "Content-Type: application/json" \
            -d "$(jq -n --arg content "$(cat updated-queue.json | jq -Rs .)" \
              '{files: {"queue.json": {"content": $content}}}')" \
            https://api.github.com/gists/$GIST_ID_QUEUE
