name: Queue PR for Review

on:
  pull_request:
    types: [opened, reopened]

jobs:
  queue-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Add PR to queue
        env:
          GH_PAT: ${{ secrets.GOWRESSH_TOKEN }}
          GIST_ID_QUEUE: ${{ secrets.GIST_ID_QUEUE }}
          REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          curl -s -H "Authorization: token $GH_PAT" https://api.github.com/gists/$GIST_ID_QUEUE > gist.json

          QUEUE=$(jq -r '.files["queue.json"].content' gist.json | jq '.')

          # Check for duplicates
          EXISTS=$(echo "$QUEUE" | jq "[.[] | select(.pr == \"$PR_NUMBER\" and .repo == \"$REPO\")] | length")
          if [ "$EXISTS" -ne 0 ]; then
            echo "PR already in queue."
            exit 0
          fi

          UPDATED_QUEUE=$(echo "$QUEUE" | jq ". + [{\"pr\": \"$PR_NUMBER\", \"repo\": \"$REPO\"}]")
          echo "$UPDATED_QUEUE" > updated-queue.json

          curl -s -X PATCH -H "Authorization: token $GH_PAT" \
            -H "Content-Type: application/json" \
            -d "$(jq -n --arg content "$(cat updated-queue.json | jq -Rs .)" \
              '{files: {"queue.json": {"content": $content}}}')" \
            https://api.github.com/gists/$GIST_ID_QUEUE
